using Content.Client.Wedding;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.WeddingRing.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class WeddingRingWindow : DefaultWindow
    {
        public event Action<int>? OnSpritePicked;

        public WeddingRingWindow()
        {
            RobustXamlLoader.Load(this);

            // SpriteList.OnItemSelected += e => OnSpritePicked?.Invoke(e.ItemIndex);
        }

        public void Populate(List<WeddingCoupleEntry> entries)
        {
            CoupleList.Clear();
            foreach (var entry in entries)
            {
                CoupleList.AddItem(entry.Name, entry.Icon);
            }
        }
    }
}
